---
- hosts: nodes

  vars: 
    packages:
      - python-dev
      - python-pip
      - gcc
      - python-setuptools
      - git-core
      - python-setuptools
      - debconf-utils

  tasks: 
    - name: Install list of packages
      apt: name={{item}} state=installed update_cache=yes
      with_items:
        - python-dev
        - python-pip
        - gcc
        - python-setuptools
        - git-core
        - python-setuptools
        - debconf-utils
      become: yes

    # emit a debug message with each package
    - debug:
        msg: "{{ item }}"
      with_items: "{{packages}}"

    # Combine the two commands to install a list of packages